[[[invalid]]]
[undefined]
replacer="undefined"

[[[main]]]
[[if]]
[1]
type="Lable"
flow=2
ctx="if($con){$true}else{$false};\n"
[con]
type="Lable"
flow=0
ui_source="con"
[true]
type="Lable"
flow=0
slot=1
ui_source="true"
[false]
type="Lable"
flow=0
slot=1
ui_source="false"

[[entry]]
[1]
type="Lable"
flow=1
ctx="let $[0 ,];\n"
[add]
type="Button"
ui_source="add"
flow=3

[[for_in]]
[1]
type="Lable"
flow=2
ctx="for(let item in $object){$body};\n"
[object]
type="Label"
ui_source="object"
flow=0
[body]
type="Label"
ui_source="body"
flow=0
slot=1
[item]
type="Label"
ui_source="item"
flow=1
slot=1
ctx="$item"


[[for_each]]
[1]
type="Lable"
flow=2
ctx="$arr.forEach((item, i)=>{$body});\n"
[arr]
type="Label"
ui_source="arr"
flow=0
[body]
type="Label"
ui_source="body"
flow=0
slot=1
[item]
type="Label"
ui_source="item"
flow=1
slot=1
ctx="$item"
[i]
type="Label"
ui_source="i"
flow=1
slot=1
ctx="$i"

[[int]]
[counter]
type="Counter"
ui_source=0
flow=1
ctx="$counter"

[[compare]]
[a]
type="Label"
ui_source="a"
flow=0
[c]
type="Items"
ui_source=["!=", "==", ">=", "<=", ">", "<", "!==", "==="]
flow=1
ctx="($a $c $b)"
[b]
type="Label"
ui_source="b"
flow=0

[[operator]]
[a]
type="Label"
ui_source="a"
flow=0
[c]
type="Items"
ui_source=["+", "-", "*", "/", "&", "|", "^", "<<", ">>"]
flow=1
ctx="($a $c $b)"
[b]
type="Label"
ui_source="b"
flow=0

[[not]]
[a]
type="Label"
ui_source="a"
flow=2
ctx="!($a)"

[[set_local]]
[1]
type="Label"
flow=2
ctx="$local = $b"
[local]
type="Items"
ui_source=[]
flow=3
[b]
type="Label"
ui_source="setter"
flow=0

[[set_global]]
[1]
type="Label"
flow=2
ctx="$global = $b"
[global]
type="Items"
ui_source=[]
flow=3
[b]
type="Label"
ui_source="setter"
flow=0

[[color]]
[color]
type="Colorer"
ui_source=0xffffff
flow=1
ctx="$color"

[[code]]
[1]
type="Label"
flow=2
ctx="$edit"
[edit]
type="Block"
ui_source="//console.log()"
flow=3

[[func]]
[edit]
type="Block"
ui_source="//return 1"
flow=1
ctx="new Function(`$edit`)"


[[return]]
[1]
type="Lable"
flow=0
ctx="return ($value);"
[value]
type="Lable"
flow=0
ui_source="value"